### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by JarYe** [bytedance/android-inline-hook#5]
### shadowhook Version

1.0.3

### Android OS Version

10

### Android ABIs

armeabi-v7a, arm64-v8a

### Device Manufacturers and Models

any

### Describe the Bug

[CXX1405] error when building with cmake using /Users/jarrettye/Documents/Workspace/Android/InlineHookDemo/app/src/main/cpp/CMakeLists.txt: Build command failed.
Error while executing java process with main class com.google.prefab.cli.AppKt with arguments {--build-system cmake --platform android --abi arm64-v8a --os-version 21 --stl c++_static --ndk-version 21 --output /Users/jarrettye/Documents/Workspace/Android/InlineHookDemo/app/.cxx/Debug/52k576n3/prefab/arm64-v8a/prefab /Users/jarrettye/.gradle/caches/transforms-3/c46ec3f0af32bc2a9539f97e0d92f6fd/transformed/shadowhook-1.0.3/prefab}

Exception in thread "main" java.lang.IllegalArgumentException: Only schema_version 1 is supported. shadowhook uses version 2.
	at com.google.prefab.api.Package.<init>(Package.kt:46)
	at com.google.prefab.cli.Cli$packages$2.invoke(Cli.kt:124)
	at com.google.prefab.cli.Cli$packages$2.invoke(Cli.kt:95)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.google.prefab.cli.Cli.getPackages(Cli.kt)
	at com.google.prefab.cli.Cli.validate(Cli.kt:172)
	at com.google.prefab.cli.Cli.run(Cli.kt:189)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:168)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:16)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:258)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:255)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:273)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:298)
	at com.google.prefab.cli.AppKt.main(App.kt:28)

**Comment by caikelun** [comment]
Please upgrade the gradle version of your project and try again. Also, compare the configuration differences between your own project and the sample project.

**Comment by caikelun** [comment]
@JarYe,

Hi, I just added a note to the readme file:

> **Note**: shadowhook uses the [prefab package schema v2](https://github.com/google/prefab/releases/tag/v2.0.0), which is configured by default since [Android Gradle Plugin 7.1.0](https://developer.android.com/studio/releases/gradle-plugin?buildsystem=cmake#7-1-0). If you are using Android Gradle Plugin earlier than 7.1.0, please add the following configuration to gradle.properties:
>
> ```
> android.prefabVersion=2.0.0
> ```

**Comment by JarYe** [comment]
Thx, Problem Solved
